### ISSUE TITLE
Decide on the features to use

### ISSUE THREAD

**Issue by epistimi4** [epistimi4/emotion_based_music_recomendation#14]
Decide which features to use from raw audio data

**Comment by epistimi4** [comment]
Feature - Why?
Energy Entropy -
Beat-
Spectral Rolloff- Spectral rolloff can be also treated as a spectral shape descriptor of an
audio signal and can be used for discriminating between voiced and unvoiced
sounds [7,5]. It can also be used to discriminate between different types of
music tracks.
Spectral Energy-
Zero crossing rate - displays the noisiness of a signal. it is used for music genre classification tasks
MFCC- used for music genre classification
Chroma vector - This is a widely used descriptor, mostly in music-related
applications
Harmonic Ratio- measuring how much periodic the signal is

**Comment by matsarou** [comment]
In order to do this we must first find the most representative features. This can be done in two ways:
- manually, by viewing the content of each cluster of songs and then setting a label
- automatically(with automatic labelling of the clusters). I read a paper with automatic labelling but seemed a little complicated.
@tyiannak what is your opinion? Can we do it manually, in case we don't manage to implement the automatic way?

**Comment by epistimi4** [comment]
@matsarou @athinabikaki  @natalitsa I believe we can select this features according to the theory provided by the class. I have stated a few points about the features I believe we should include in the document. 
https://docs.google.com/document/d/1c8C3ut2m2XPe7YBw23wbve2slCsOIVzQbIzeTj9nqAw/edit#
Please revise and if you agree on my points, we can close this task.

**Comment by tyiannak** [comment]
I would use all features in the beginning and then do some feature selection / dimensionality reduction at a second stage. Alternatively you could study each feature / statistics separately based on its discrimination ability on the classification / regression task.

**Comment by epistimi4** [comment]
Lets use all the provided by the library features as suggested
