### ISSUE TITLE
datasheet preprocessing

### ISSUE THREAD

**Issue by epistimi4** [epistimi4/emotion_based_music_recomendation#15]
remove outliers, clean datasheet

- In case of multiple tags for one song and different users, we should tag the song according to the majority

**Comment by matsarou** [comment]
As part of the preprocessing we can group the features. For example the loudness could become:
{LowLoudness,MedLoudness,HighLoudness}.

I propose to create three or four classes, concerning the numeric features.

**Comment by matsarou** [comment]
I report some issues I saw:

- The spotify cannot always find the songs. There is a 40% data loss. Most of the songs have a title compatible with youtube.

- There will be incompatible entries  between Spotify and Youtube. Some songs found by youtube, but missing from spotify and vice versa.

- The 'Not found' spotify and youtube metadata must be recorded as 'NaN' in the dataset. I designed the classifier to drop null features. 

- We can discuss the possibility to have copied versions of data one for youtube and another for spotify, to avoid data loss.

**Comment by matsarou** [comment]
@athinabikaki please write the progress on that issue, and when do you think that we will have it.

**Comment by athinabikaki** [comment]
I completed my datasets with Spotify metadata from 4 users:

Spotify found all songs

Built dataset final dataset with spotify metadata from 4 users. To be completed with all remaining data.
@matsarou I agree with you, I will mark Not found songs as 'NaN' in the final dataset.
@epistimi4 in order to read this dataset I included a draft version under the name athina_playlist_metadata.xlsx in the /data folder. I'm going to merge these codes as a unified step of preprocessing.

**Comment by athinabikaki** [comment]
All user data preprocessed and uploaded. Final unified dataset with Spotify metadata and user info is also uploaded under the name athina_playlist_metadata.xlsx
Some basic visualizations also included.

**Comment by athinabikaki** [comment]
Data preprocessing is completed and the following tasks were prioritized:
-  Data collection
-  **Data cleaning**
-  Data visualizations
-  Data not found in  Spotify were removed (prerequisite for correlating spotify metadata with user context)
