### ISSUE TITLE
Complete the progress in the report 

### ISSUE THREAD

**Issue by epistimi4** [epistimi4/emotion_based_music_recomendation#3]
At the end of the milestone record the progress of every single task in a report, which will be part of the final report

**Comment by matsarou** [comment]
@natalitsa 

> This task also includes the exact definition of the data format.

The domain objects will be created as part of this task, as per

**Comment by natalitsa** [comment]
For the milestone Dataset Phase 1, we still have one open issue. So I created the report here https://docs.google.com/document/d/1c8C3ut2m2XPe7YBw23wbve2slCsOIVzQbIzeTj9nqAw/edit?usp=sharing
but we may need to make some modifications later.
I will close this issue here and create a new one that will be part of the milestone Dataset Phase 2
